on: push
name: âš› React CI Test
jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - name: ğŸ” Searching for Repo
        uses: actions/checkout@v2

      - name: â™»ï¸ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ‘¤ npm ci, ğŸ”¨build and ğŸ§ªï¸test
        run: |
          npm ci --no-optional
          npm run build --if-present
          npm test
